---
#
# Project:: Ansible Role - Docker Host
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Install and configure Docker and Docker Compose

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.gpg_armored

- name: De-Armor and install Docker GPG key
  shell: "gpg --dearmor < /usr/share/keyrings/docker.gpg_armored > /usr/share/keyrings/docker.gpg"
  args:
    creates: /usr/share/keyrings/docker.gpg

- name: Add the Docker repository
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Refresh apt cache
  apt:
    update-cache: yes

- name: Install Docker and Docker Compose
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-compose

- name: Install the prerequisites for Docker container management via Ansible
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-dev
      - python3-pip
      - openssl
      - linux-image-extra-virtual # https://github.com/docker/docker/issues/15825

- name: Install required python packages
  pip:
    name: "{{ packages }}"
    executable: pip3
    state: present
    break_system_packages: true
  vars:
    packages:
      - six
      - setuptools
      - passlib

- name: Verify the Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
