---
#
# Project:: Ansible Role - Docker Host
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Install and configure the core requirements for working with Docker on Ubuntu-based systems.

- import_tasks: docker.yml
  when: ansible_distribution == 'Ubuntu'
